# SPDX-License-Identifier: MIT
---
common_network_interfaces:
  - name: eth0
    ipv6_address: "2001:41d0:c:67:1::199/128"
    dns: "{{ dns_servers }}"
    routes:
      - dest: "0.0.0.0/0"
        gw: "169.254.0.1"
        onlink: true
      - dest: "::/0"
        gw: "fe80::1"
