# SPDX-License-Identifier: MIT
---
argument_specs:
  main:
    short_description: Configure base system
    options:
      common_timezone:
        type: str
        default: Etc/UTC
        description: System timezone (e.g., Europe/Paris, Etc/UTC).
