# SPDX-License-Identifier: MIT
---
# Proxy config
nginx_proxy_tls_cert_path: /var/lib/lego/certificates/txadmin.crt
nginx_proxy_tls_key_path: /var/lib/lego/certificates/txadmin.key

nginx_proxy_txadmin_fqdn: "{{ cfx_server_txadmin_endpoint }}"
