# SPDX-License-Identifier: MIT
---
- name: Install restic
  ansible.builtin.apt:
    name: restic
    state: present

- name: Ensure group exists
  ansible.builtin.group:
    name: "{{ restic_group }}"
    system: true
    state: present

- name: Create restic system user
  ansible.builtin.user:
    name: "{{ restic_user }}"
    group: "{{ restic_group }}"
    system: true
    home: "{{ restic_home }}"
    shell: /usr/sbin/nologin
    state: present

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_user }}"
    mode: "0700"
  loop:
    - "{{ restic_dump_dir }}"
    - "{{ restic_cache_dir }}"

- name: Setup MariaDB requirements
  ansible.builtin.import_tasks: mariadb.yml
  when: restic_mariadb_backup

- name: Setup OpenLDAP requirements
  ansible.builtin.import_tasks: openldap.yml
  when: restic_openldap_backup

- name: Deploy excludes file
  ansible.builtin.copy:
    content: "{{ restic_exclude_patterns | join('\n') }}"
    dest: "{{ restic_home }}/excludes.txt"
    owner: "{{ restic_user }}"
    group: "{{ restic_user }}"
    mode: "0640"

- name: Deploy backup scripts
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/usr/local/sbin/{{ item }}"
    owner: root
    group: "{{ restic_group }}"
    mode: "0750"
  loop:
    - backup.sh
    - backup-check.sh

- name: Check if encrypted credential exists
  ansible.builtin.stat:
    path: /etc/credstore.encrypted/restic
  register: restic_cred_file

- name: Generate and encrypt private key
  when: not restic_cred_file.stat.exists
  block:
    - name: Encrypt private key with systemd-creds
      community.general.systemd_creds_encrypt:
        secret: "{{ restic_private_key.stdout }}"
      register: restic_encrypted_creds

    - name: Save encrypted credential
      ansible.builtin.copy:
        content: "{{ restic_encrypted_creds.value }}"
        dest: /etc/credstore.encrypted/restic
        owner: root
        group: restic
        mode: "0640"

- name: Install systemd services for backup
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: "0644"
  loop:
    - restic.service
    - restic-check.service
    # - restic-off-site.service
  notify: Reload systemd

- name: Check if Restic repository is already initialized
  ansible.builtin.command: restic snapshots
  register: restic_check
  failed_when: false
  changed_when: false
  environment:
    RESTIC_CACHE_DIR: "{{ restic_cache_dir }}"
    RESTIC_REPOSITORY: "{{ restic_repo_path }}"
    RESTIC_PASSWORD: "{{ restic_password }}"
    AWS_ACCESS_KEY_ID: "{{ restic_password }}"
    AWS_SECRET_ACCESS_KEY: "{{ restic_password }}"

- name: Initialize Restic backup repository
  ansible.builtin.command: restic init
  when: restic_check.rc != 0
  changed_when: true
  environment:
    RESTIC_CACHE_DIR: "{{ restic_cache_dir }}"
    RESTIC_REPOSITORY: "{{ restic_repo_path }}"
    RESTIC_PASSWORD: "{{ restic_password }}"
    AWS_ACCESS_KEY_ID: "{{ restic_password }}"
    AWS_SECRET_ACCESS_KEY: "{{ restic_password }}"

- name: Ensure Restic cache directory is owned by the restic user
  ansible.builtin.file:
    path: "{{ restic_cache_dir }}"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    recurse: true

- name: Install systemd timers
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    mode: "0644"
  loop:
    - restic.timer
    - restic-check.timer
  notify: Reload systemd

- name: Activate systemd timers
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - restic.timer
    - restic-check.timer
