# SPDX-License-Identifier: MIT
---
- name: Install mariadb-backup
  ansible.builtin.apt:
    name: mariadb-backup
    state: present

- name: Create restic mysqld database user
  ansible.mariadb.mariadb_user:
    name: "{{ restic_user }}"
    host: localhost
    plugin: unix_socket
    priv: "*.*:RELOAD, PROCESS, LOCK TABLES, BINLOG MONITOR"
    state: present

- name: Add restic user to the mysql group
  ansible.builtin.user:
    name: "{{ restic_user }}"
    groups: mysql
    append: true
