# SPDX-License-Identifier: MIT
---
_cfx_server_github_base: https://api.github.com/repos/citizenfx/fivem/commits/v1.0.0.
_cfx_server_artifacts_base: https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/

_cfx_server_depot_url: https://depot.cfx.re/public/p/fxserver_gen9/u/main
