# SPDX-License-Identifier: MIT
---
# Install
cfx_server_type: legacy
cfx_server_build_number: 35245

# txAdmin config
cfx_server_txadmin_endpoint: txadmin.dev.coursepoursuite.fr
cfx_server_account: Carbonaraaaaa:16402109

# Database
cfx_server_db_host: db.coursepoursuite.fr
cfx_server_db_name: fivem_dev
cfx_server_db_user: cfx_dev
cfx_server_db_pass: "{{ vault_cfx_server_db_pass }}"
