# SPDX-License-Identifier: MIT
---
# SSH config to support vscode remote development
sshd_global_config:
  AddressFamily: any

sshd_match_blocks:
  - condition: Group dev
    rules:
      AllowTcpForwarding: "yes"
      AllowStreamLocalForwarding: "yes"
