# SPDX-License-Identifier: MIT
---
- name: Install common packages
  ansible.builtin.apt:
    name:
      - bash-completion
      - dnsutils
      - htop
      - iproute2
      - logrotate
      - mtr-tiny
      - unattended-upgrades
      - vim
    state: present
    update_cache: true
    cache_valid_time: 3600

# - name: Set hostname from inventory_hostname
#   ansible.builtin.hostname:
#     name: "{{ inventory_hostname_short }}"
#     use: debian

# - name: Configure hosts file from inventory_hostname
#   ansible.builtin.template:
#     src: hosts.j2
#     dest: /etc/hosts
#     mode: "0644"

- name: Set timezone via localtime
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Ensure systemd-resolved is installed
  ansible.builtin.apt:
    name: systemd-resolved
    state: present

- name: Disable unused defaults in systemd-resolved
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?{{ item.key }}\b'
    line: "{{ item.key }}={{ item.value }}"
    firstmatch: true
    state: present
  loop:
    - { key: LLMNR, value: "false" }
  notify: Reload systemd-resolved
