# SPDX-License-Identifier: MIT
---
mariadb_bind_address: "::"
mariadb_trusted_network: "2001:41d0:c:67:1::/72"

mariadb_databases:
  - name: fivem_legacy
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4
    state: present
  - name: fivem_dev
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4
    state: present

mariadb_users:
  - name: cfx_legacy
    host: 2001:41d0:c:67:1::dead
    password: "{{ vault_cfx_legacy_pass }}"
    priv: "fivem_legacy.*:ALL"
  - name: cfx_dev
    host: 2001:41d0:c:67:1::cafe
    password: "{{ vault_cfx_dev_pass }}"
    priv: "fivem_dev.*:ALL"

mariadb_pam_enable: true
mariadb_pam_users: "{{ vault_mariadb_pam_users }}"
