# SPDX-License-Identifier: MIT
---
- name: Deploy game servers
  hosts: games
  gather_facts: false
  roles:
    - role: cfx_server
      tags: ["cfx"]

- name: Deploy developement environement
  hosts: dev
  gather_facts: false
  roles:
    - role: bindfs
      tags: ["bindfs"]
