# SPDX-License-Identifier: MIT
---
- name: Configure base operating system
  hosts: all
  gather_facts: false
  roles:
    - role: common
      tags: ["common"]
    - role: networkd
      tags: ["network"]
    - role: nftables
      tags: ["nftables"]
    - role: sshd
      tags: ["sshd"]
    - role: sssd
      tags: ["sssd"]
